@startuml
!include <C4/C4_Context.puml>

title Диаграмма контекста для системы Теплый Дом
Person(client, "Клиент", "Пользователь системы")
Person(admin, "Администратор", "Администратор системы")
Person(master, "Монтажник", "Специалист по подключению оборудования")
System(monolith, "Монолит", "Система теплый дом")
System_Ext(sensorApi, "API сервисы (~x100)", "сервисы для получения информации о температуре в подключенных домах")
Rel(client, monolith, "выполняет HTTP запросы для получения данных о температуре в доме клиента", "HTTP/json")
Rel(admin, monolith, "выполняет HTTP запросы для изменения информации о датчиках в системе", "HTTP/json")
Rel(master, monolith, "выполняет HTTP запросы для регистрации датчиков в системе", "HTTP/json")
Rel(monolith, sensorApi, "выполняет HTTP запросы для получения данных о температуре в подключенных домах", "HTTP/json")
Rel(master, sensorApi, "использует информацию о датчиках для регистрации их в системе")
@enduml
